spring.application.name=auth-identity-service
server.port=8484

# JWT (ejemplo inicial; en producción usar clave fuerte en variables de entorno)
security.jwt.secret=kY+FNJ/HIRdG/mpLHGWL4mRfSGyknywI3bp8PmCdGho=
security.jwt.issuer=auth-identity-service
security.jwt.audience=clinic-backend
security.jwt.access-token-expiration=900       
security.jwt.refresh-token-expiration=2592000   




# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect






# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Spring Cloud Stream - function/binding (ejemplo)
spring.cloud.stream.function.definition=userCreated
spring.cloud.stream.bindings.userCreated-out-0.destination=user.events
spring.cloud.stream.bindings.userCreated-out-0.contentType=application/json

spring.cloud.stream.rabbit.bindings.userCreated-out-0.producer.routing-key-expression='user.created'
