# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (SQLite)
# ===============================
# Crea un archivo llamado jclinical.db en la raíz de tu proyecto
spring.datasource.url=jdbc:sqlite:jclinical.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# Le indicamos que use el dialecto comunitario para entender SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 'update' creará la tabla 'expedientes' automáticamente al iniciar la app
spring.jpa.hibernate.ddl-auto=update

# ===============================
# HERRAMIENTAS DE DESARROLLO
# ===============================
# Muestra en la consola las consultas SQL que Spring hace por detrás
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true