# =====================================================
# PATIENT SERVICE - Application Configuration
# =====================================================

# Application Name
spring.application.name=patient-service
server.port=8585

# =====================================================
# PostgreSQL Database Configuration
# =====================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_service_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# =====================================================
# JPA/Hibernate Configuration
# =====================================================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =====================================================
# JWT Configuration (debe coincidir con Auth Service)
# =====================================================
security.jwt.secret=kY+FNJ/HIRdG/mpLHGWL4mRfSGyknywI3bp8PmCdGho=
security.jwt.issuer=auth-identity-service
security.jwt.audience=clinic-backend


# =====================================================
# RabbitMQ Configuration
# =====================================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Exchange, queues y routing keys de Patient Service
app.rabbitmq.exchange.patients=patients.exchange

app.rabbitmq.queue.patient-created=patient.created.queue
app.rabbitmq.queue.patient-updated=patient.updated.queue
app.rabbitmq.queue.patient-deactivated=patient.deactivated.queue

app.rabbitmq.routing-key.patient-created=patient.created
app.rabbitmq.routing-key.patient-updated=patient.updated
app.rabbitmq.routing-key.patient-deactivated=patient.deactivated


# =====================================================
# Eureka Client Configuration
# =====================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# =====================================================
# Actuator Configuration
# =====================================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

